# Para ver a documentação interativa acesse: https://editor.swagger.io/

openapi: 3.0.1
info:
  title: Portal da Transparência - API
  version: 1.0.0
  description: >
    Esta é a documentação da API do Portal da Transparência do condomínio, 
    que permite o acesso a dados como despesas, receitas, meses cadastrados, entre outros.

servers:
  - url: http://localhost/projeto-controle-php/api
    description: Servidor local (XAMPP)

paths:

  /cadastrar_usuario.php:
    post:
      summary: Cadastra um novo usuário
      description: >
        Recebe os dados via POST, valida a senha e confirmação, evita e-mails duplicados e insere o usuário no banco com a senha criptografada.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: Danilo Freitas
                email:
                  type: string
                  example: danilo@email.com
                senha:
                  type: string
                  example: senha123
                confirmar_senha:
                  type: string
                  example: senha123
              required:
                - nome
                - email
                - senha
                - confirmar_senha
      responses:
        '200':
          description: Usuário cadastrado com sucesso
        '400':
          description: Dados inválidos ou e-mail já cadastrado
        '500':
          description: Erro interno ao cadastrar usuário




  /listar_meses.php:
    get:
      summary: Lista os meses com registros financeiros
      description: Retorna uma lista com os meses disponíveis, conforme os registros no banco de dados.
      responses:
        '200':
          description: Lista de meses cadastrados com pelo menos um pagamento
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "Julho"
        '500':
          description: Erro interno no servidor